branches:
  - label: feature
    prefix: feature/
  - label: documentation
    prefix: docs/
  - label: enhancement
    prefix: enhancement/
  - label: bug
    prefix: bugfix/
  - label: misc
    prefix: misc/
  - label: '*'
    prefix: issues/
