name: Build project

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B -U clean install --file pom.xml
